config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

stock/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

stock/exchange/urls.py
from django.urls import path

from . import views

app_name = 'exchange'

urlpatterns = [
    path('', views.index, name='index'),
    path('/<str:symbol>/', views.stock_list_page, name='stock_list_page'),
    #path('/', views.stock_list_page, name='stock_list'),
    path('buy/', views.buy, name='buy'),
    path('sell/', views.sell, name='sell'),
    path('mypage/', views.mypage, name='mypage')
    #path('article/create/', views.article_create, name='article_create'),
    #path('comment/create/<int:article_id>/', views.comment_create, name='comment_create'),
]

stock/mainboard/urls.py
from django.urls import path

from . import views

app_name = 'mainboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('article/create/', views.article_create, name='article_create'),
    path('comment/create/<int:article_id>/', views.comment_create, name='comment_create'),
]

stock/news/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
]

stock/stock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("common.urls")),
    path("common/", include("common.urls")),
    path("admin/", admin.site.urls),
    path("news/", include("news.urls")),
    path("api/", include("rest_api.urls")),
    path("mainboard/", include("mainboard.urls")),
    path("exchange/", include("exchange.urls"))
    # path('', views.index, name='index'), # 홈화면으로 리다이렉트
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stock/mainboard/models.py
from django.db import models

class Article(models.Model):
    subject = models.CharField(max_length=100)
    content = models.TextField()
    create_date = models.DateTimeField()
    # 글쓴이 추가 예정
    
    def __str__(self):
        return self.subject

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    # 코멘트 단 이 추가 예정

    def __str__(self):
        return self.content

stock/news/models.py
from django.db import models


class News(models.Model):
    subject = models.TextField()
    content = models.TextField()
    created_date = models.TextField()
    keyword = models.TextField()
    url = models.TextField()

    def __str__(self):
        return self.subject


class Column(models.Model):
    subject = models.TextField()
    url = models.TextField()

    def __str__(self):
        return self.title

stock/rest_api/models.py
from django.db import models

# Create your models here.

stock/mainboard/forms.py
from django import forms
from mainboard.models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['subject', 'content']


        labels = {
            'subject': '제목',
            'content': '내용',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

stock/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm, SignupForm

def home(request):
    """
    홈페이지
    """
    
    return render(request, 'common/home.html')

def signup(request):
    """
    계정생성
    """
    
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username') # 이름 가져오기
            raw_password = form.cleaned_data.get('password1') # 비밀번호 가져오기
            user = authenticate(username=username, password=raw_password) # 회원가입 후 자동 로그인 : authenticate
            login(request, user)
            return redirect('mainboard:index')
    else:
        form = SignupForm()
    return render(request, 'common/signup.html', {'form': form})

stock/exchange/views.py
##### 주식 데이터, 그래프 관련 #####
import io
import urllib, base64
import FinanceDataReader as fdr
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.ticker as ticker
import matplotlib.font_manager as fm
from mplfinance.original_flavor import candlestick2_ohlc
########################################################
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf import settings
from .models import Stock_list, User_result, Transaction_history
from common.models import MyUser
from django.utils import timezone
from django.core.paginator import Paginator # 페이징 관련 (글 목록)
from django.db.models import Q # 검색 관련
from datetime import datetime, timedelta


# Create your views here.
def index(request):
    
#  ---------------------------------- 검색  ---------------------------------- #
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어

    # 조회
    stock_list = Stock_list.objects.order_by('stock_name')
    if kw:
        stock_list = stock_list.filter(
            # contains : 대소문자 구분 / icontain : 대소문자 구분x
            Q(symbol__icontains=kw) |  # 종목 번호
            Q(stock_name__icontains=kw)  # 종목 이름 
        ).distinct()
# ---------------------------------------------------------------------------- #

# ----------------------------------- [페이징] --------------------------- #
    # 페이징처리
    paginator = Paginator(stock_list, 20)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'stock_list': page_obj, 'page': page, 'kw': kw}  # page와 kw가 추가되었다.
    print('kw:', kw)

    # context = {'stock_list': stock_list}
    return render(request, 'exchange/stock_list.html', context)
# ----------------------------------- [페이징] --------------------------- #


# 예은 : 그래프 만드는 부분 추가했습니다 (21.02.01)
# 예은 할일 : cur_price를 현재가로 불러오도록 (근데 이렇게하면 실시간 업데이트 or 호가창 필요), 전일대비 몇퍼 증감인지 보여주기
def stock_list_page(request, symbol):
    today = datetime.today()
    yesterday = datetime.today() - timedelta(days=1)
    stock = Stock_list.objects.get(symbol=symbol)

    df_specific = fdr.DataReader(symbol, today.strftime('%Y-%m-%d'))
    stock.cur_price = int(df_specific['Close'][0]) # 맨위 날짜 읽는거니까 오늘 정가 empty여도 가장 최근값 불러옴

    # 전일 데이터 불러오기 (주말, 연휴인 경우 data없으므로 data있을때까지 거슬러올라가기)
    yesterday_stock = fdr.DataReader(symbol, yesterday.strftime('%Y-%m-%d'))
    date = 1
    while (1):
        yesterday_stock = fdr.DataReader(symbol, yesterday.strftime('%Y-%m-%d'), today.strftime('%Y-%m-%d'))
        if (len(yesterday_stock) > 1):
            yesterday_price = int(yesterday_stock['Close'][0])
            break
        else:
            date += 1
            yesterday = datetime.today() - timedelta(days=date)
    yesterday_price = int(yesterday_stock['Close'][0])

    difference = stock.cur_price - yesterday_price
    difference_percent = round((difference / yesterday_price) * 100, 2)
    # 색깔을 위한 Flag
    if difference > 0:
        flag = 1
    elif difference < 0:
        flag = -1
    else:
        flag = 0

    graph_uri = graph(request, symbol)

    context = {'stock': stock, 'data': graph_uri, 'yesterday':yesterday_price, 'difference':difference, 'diff_per':difference_percent, 'flag':flag}
    return render(request, 'exchange/stock_page.html', context)



def find_stock(request):
    if request.user.is_authenticated:
        userID = request.user.id
    stock_requested = str(request.GET.get('stock_name', None))
    stock_list = stock_requested.objects.get(id=stock_name)
    context = {'stock_list': stock_list}
    return render(request, 'exchange/stock_list_page.html', context)


def graph(request, symbol):
    stock = Stock_list.objects.get(symbol=symbol)
    title_font_name = 'sans-serif'
    tick_label_font_name = 'sans-serif'

    # 봉차트 그리기
    now = datetime.now()
    half_year = (now - timedelta(days=180)).strftime('%Y-%m-%d')
    df_specific = fdr.DataReader(symbol, half_year)

    df_specific['MA5'] = df_specific['Close'].rolling(5).mean()
    df_specific['MA10'] = df_specific['Close'].rolling(10).mean()
    df_specific['MA20'] = df_specific['Close'].rolling(20).mean()
    df_specific[['Close','MA5','MA10','MA20']].plot()

    fig = plt.figure(figsize=(20,10))
    ax = fig.add_subplot(111)
    index = df_specific.index.astype('str') # 캔들스틱 x축이 str로 들어감

    # 이동평균선 그리기
    ax.plot(index, df_specific['MA5'], label='5days MA', linewidth=0.7)
    ax.plot(index, df_specific['MA10'], label='10days MA', linewidth=0.7)
    ax.plot(index, df_specific['MA20'], label='20days MA', linewidth=0.7)

    # X축 티커 숫자 20개로 제한
    ax.xaxis.set_major_locator(ticker.MaxNLocator(20))

    # 그래프 title과 축 이름 지정
    # ax.set_title(stock_name, fontsize=22)
    ax.set_xlabel('Date')

    # 캔들차트 그리기
    candlestick2_ohlc(ax, df_specific['Open'], df_specific['High'],
                      df_specific['Low'], df_specific['Close'],
                      width=0.5, colorup='r', colordown='b')
    ax.legend()
    plt.grid()

    plt.plot()
    fig = plt.gcf()
    buf = io.BytesIO()
    fig.savefig(buf, format='png')
    buf.seek(0)
    string = base64.b64encode(buf.read())
    uri = urllib.parse.quote(string)
    return uri


# get username, stockID, quantity from get request 
# find cur_price from Stock_list
# find cash from MyUser
# return : cash, cur_price

def request_stockinfo(userID, stockID):
    cur_price = int(Stock_list.objects.get(symbol=stockID).cur_price)
    cur_cash = int(MyUser.objects.get(id=userID).cash)
    return (cur_price, cur_cash)

# returns whether buy is possible
def judge_buy(cash, cur_price, quantity):
    
    if cash < cur_price * quantity:
        return False
    else:
        return True

# returns whether sell is possible
def judge_sell(userID, stockID, quantity):
    #Check if user has enough stocks to sell
    try:
        user_result = User_result.objects.get(user_ID=userID, stock_ID=stockID)
        if user_result.total_Qty < quantity:
            return False
        else:
            return True
    except:
        return False


###################################################
# function buy() : Buy Stocks                     #
# url : /buy?stockID=XXXXXX&quantity=YYYYYY       #
# stockID = XXXXXX                                #
# quantity = YYYYYY                               #
# 1. Check if user has enough stock : judge_buy() #
# 2. Save Transaction_history                     #
# 3. update user.cash, user_result.total_Qty      #
#    (function : transaction_save())              #
###################################################
def buy(request):
    if request.user.is_authenticated:
        userID = request.user.id
    stockID = str(request.GET.get('stockID', None))
    quantity = int(request.GET.get('quantity', None))
    ##Add Check if quantity is 0

    ########################
    user = MyUser.objects.get(id=userID)
    stock = Stock_list.objects.get(symbol=stockID)
    cur_price = int(stock.cur_price)
    cur_cash = int(user.cash)

    buy_available = judge_buy(cur_cash, cur_price, quantity)
    if buy_available:
        #save transaction history
        new_transaction = Transaction_history(Qty=quantity, cur_price=cur_price, date=str(timezone.now()), purchase=1, stock_ID=stock, user_ID=user)
        new_transaction.save()
        #Update user_result
        transaction_save(user, stock, quantity, 1)
        updated_cash = user.cash
        #Buy Success
        return HttpResponse("Buy Success : userID %s, quantity %s, Old cash %s, Current cash %s, cur_price : %s" % (userID, quantity, cur_cash, updated_cash, cur_price))
    else:
        #Buy Failed
        return HttpResponse("Buy Failed : userID %s, quantity %s, Current cash %s, cur_price : %s, need more : %s" % (userID, quantity, cur_cash, cur_price, cur_price*quantity-cur_cash))


###################################################
# function sell() : sell Stocks                   #
# url : /sell?stockID=XXXXXX&quantity=YYYYYY      #
# stockID = XXXXXX                                #
# quantity = YYYYYY                               #
# 1. Check if user has enough stock : judge_sell()#
# 2. Save Transaction_history                     #
# 3. update user.cash, user_result.total_Qty      #
#    (function : transaction_save())              #
###################################################
def sell(request):
    if request.user.is_authenticated:
        userID = request.user.id
    stockID = str(request.GET.get('stockID', None))
    quantity = int(request.GET.get('quantity', None))
    ##Add Check if quantity is 0

    ########################
    user = MyUser.objects.get(id=userID)
    stock = Stock_list.objects.get(symbol=stockID)
    cur_price = int(stock.cur_price)
    cur_cash = int(user.cash)
    sell_available = judge_sell(user.id, stock.id, quantity)
    user_result = User_result.objects.get(user_ID=userID, stock_ID=stock.id)

    if sell_available:
        #save transaction history
        new_transaction = Transaction_history(Qty=quantity, cur_price=cur_price, date=str(timezone.now()), purchase=0, stock_ID=stock, user_ID=user)
        new_transaction.save()
        #Update user_result
        transaction_save(user, stock, quantity, 0)
        updated_cash = user.cash
        # Sell Success
        return HttpResponse("Sell Success : userID %s, sell quantity %s,remain quantity %s, Old cash %s, Current cash %s, cur_price : %s" % (userID, quantity, user_result.total_Qty, cur_cash, updated_cash, cur_price))
    else:
        # Sell failed
        return HttpResponse("Sell Failed : userID %s, quantity %s" % (userID, quantity))




#########################################################
# function transaction_save() : update user_result      #
# type : buy = 1, sell = 0                              #
# 1. Buy                                                #
#   1) Check if user has user_result with same stock.id #

stock/mainboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.utils import timezone
from .forms import ArticleForm, CommentForm
from .models import Article, Comment
from django.core.paginator import Paginator





def index(request):
    article_list = Article.objects.order_by('-create_date')

        # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지

        # 페이징처리
    paginator = Paginator(article_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'article_list': page_obj}
    # context = {'article_list' : article_list} <- 페이징하면서 사라짐


    # return HttpResponse("안녕하세요 pybo에 오신것을 환영합니다.")
    return render(request, 'article_list.html', context)

def detail(request, article_id):
    #article = Article.objects.get(id=article_id)
    article = get_object_or_404(Article, pk = article_id)
    context = {'article': article}
    return render(request, 'article_detail.html', context)



def article_create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.create_date = timezone.now()
            article.save()
            return redirect('mainboard:index')
    else:
        form = ArticleForm()
    context = {'form': form}
    return render(request, 'article_form.html', context)





# def comment_create(request, article_id):
#     article = get_object_or_404(Article, pk=article_id)
#     article.comment_set.create(content=request.POST.get('content'), create_date=timezone.now())
#     return redirect('mainboard:detail', article_id=article.id)

def comment_create(request, article_id):
    
    article = get_object_or_404(Article, pk=article_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.create_date = timezone.now()
            comment.article = article
            comment.save()
            return redirect('mainboard:detail', article_id=article.id)
    else:
        form = CommentForm()
    context = {'article': article, 'form': form}
    return render(request, 'article_detail.html', context)

stock/rest_api/views.py
import json
from django.shortcuts import render
from django.views.generic import View
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

# Create your views here.


@method_decorator(csrf_exempt, name="dispatch")
class IndexView(View):
    def get(self, request):
        return

    def post(self, request):
        data = json.loads(request.body)
        print(data)
        return HttpResponse(status=200)

stock/templates/article_detail.html
{% extends 'temp_base.html' %}
{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ article.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ article.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ article.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{article.comment_set.count}}개의 댓글이 있습니다.</h5>
    {% for comment in article.comment_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ comment.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ comment.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'mainboard:comment_create' article.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="댓글등록" class="btn btn-primary">
    </form>
</div>

{% endblock %}

stock/templates/article_form.html
{% extends 'temp_base.html' %}
{% block content %}

<div class="container">
        <h5 class="my-3 border-bottom pb-2">게시글 등록</h5>
        <form method="post" class="post-form my-3">
            {% csrf_token %}
            <!-- 오류표시 Start -->
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                        {% if field.errors %}
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
            <!-- 오류표시 End -->
            <div class="form-group">
                <label for="subject">제목</label>
                <input
                    type="text"
                    class="form-control"
                    name="subject"
                    id="subject"
                    value="{{ form.subject.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="content">내용</label>
                <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">저장하기</button>
        </form>
    </div>

    {% endblock %}

stock/templates/article_list.html
{% extends 'temp_base.html' %}
{% block content %}

    {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if article_list %}
        {% for article in article_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'mainboard:detail' article.id %}">{{ article.subject }}</a>
            {% comment %} 게시글에 달린 댓글 개수 표시 {% endcomment %}
            {% if article.comment_set.count > 0 %}
                <span class="text-danger small ml-2">{{ article.comment_set.count }}</span>
            {% endif %}
            {% comment %} 댓글 개수 끝 {% endcomment %}
            </td>
            <td>{{ article.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">게시글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
             
{% comment %} (... 생략 ...) 나중에 부트스트랩바꾸면 여기를 참조할것
    </table> {% endcomment %}
<!-- ------------------------------- [edit] -------------------------------- -->
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if article_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ article_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in article_list.paginator.page_range %}
            {% if page_number >= article_list.number|add:-5 and page_number <= article_list.number|add:5 %}
            {% if page_number == article_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if article_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ article_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
<!-- ----------------------------------------------------------------------- -->    

    <a href="{% url 'mainboard:article_create' %}" class="btn btn-primary">게시글 등록하기</a>
    </ul>

{% endblock %}

stock/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script>
        function getNews() {
            $.ajax({
                url: "/api/news",
                type: "POST",
                data: { mode: "news" },
                success: function (request) {

                    return
                }

            })
        }

        function getColumn() {
            $.ajax({
                url: "/api/news",
                type: "POST",
                data: { mode: "column" },
                success: function (request) {

                    return
                }

            })
        }

    </script>
</head>

<body>
    <h1>주식해커스</h1>
    <button onclick="getNews()">뉴스</button>
    <button onclick="getColumn()">칼럼</button>
    <h3>오늘의 키워드</h3>
    <a href="?keyword=HMM">HMM</a>
    <h5>검색한 키워드: {{ keyword }}</h5>
    {% for news in newses %}
    <hr>
    <h3>{{ news.subject }}</h3>
    <h4>{{ news.content }}</h4>
    <h6>{{ news.created_date }}</h6>
    <a href="{{ news.url }}">바로가기</a>
    {% endfor %}
</body>

</html>

stock/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

stock/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-light" style="background-color: #FFD800;">
    <a class="navbar-brand" href="{% url 'common:home' %}">나스닥은 신이다</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'mainboard:index' %}">게시글</a>
                <a class="nav-link" href="{% url 'exchange:index' %}">주식 매매</a>
                <a class="nav-link" href="{% url 'exchange:mypage' %}">마이페이지</a>
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                 <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

stock/templates/temp_base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>









<!-- pre-->
{% comment %} 

{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>주식 프로젝트</title>

        <!-- jQuery JS -->
    <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

</body>
</html> {% endcomment %}

<!-- pre-->

{% comment %} {% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'pybo/style.css' %}">
    <title>개미들 안뇽안뇽</title>
</head>


<body>


{% include "navbar.html" %}



<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}


<!-- jQuery JS -->
<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>


<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html> {% endcomment %}