config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

stock/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

stock/exchange/urls.py
from django.urls import path

from . import views

app_name = 'exchange'

urlpatterns = [
    path('', views.index, name='index'),
    path('/<str:symbol>/', views.stock_list_page, name='stock_list_page'),
    #path('/', views.stock_list_page, name='stock_list'),
    path('buy/', views.buy, name='buy'),
    path('sell/', views.sell, name='sell'),
    path('mypage/', views.mypage, name='mypage')
    #path('article/create/', views.article_create, name='article_create'),
    #path('comment/create/<int:article_id>/', views.comment_create, name='comment_create'),
]

stock/mainboard/urls.py
from django.urls import path

from . import views

app_name = 'mainboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('article/create/', views.article_create, name='article_create'),
    path('comment/create/<int:article_id>/', views.comment_create, name='comment_create'),
]

stock/news/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
]

stock/stock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("common.urls")),
    path("common/", include("common.urls")),
    path("admin/", admin.site.urls),
    path("news/", include("news.urls")),
    path("api/", include("rest_api.urls")),
    path("mainboard/", include("mainboard.urls")),
    path("exchange/", include("exchange.urls"))
    # path('', views.index, name='index'), # 홈화면으로 리다이렉트
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stock/exchange/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings

class Stock_list(models.Model):
    market_name = models.CharField(max_length=50)
    symbol = models.CharField(max_length=50, unique=True)
    stock_name = models.CharField(max_length=100)
    cur_price = models.IntegerField()

class Stock_search_page(models.Model):
    stock_ID = models.ForeignKey(Stock_list, on_delete=models.CASCADE)
    # 추후 필요 시, 용기 업데이트 예정

class Transaction_history(models.Model):
    user_ID = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stock_ID = models.ForeignKey(Stock_list, on_delete=models.CASCADE)
    Qty = models.IntegerField()
    cur_price = models.IntegerField()
    date = models.DateTimeField(timezone.now())
    purchase = models.BooleanField()

class User_result(models.Model):
    user_ID = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stock_ID = models.ForeignKey(Stock_list, on_delete=models.CASCADE)
    total_Qty = models.IntegerField()
    avg_purchase_price = models.IntegerField()

stock/rest_api/models.py
from django.db import models

# Create your models here.

stock/mainboard/forms.py
from django import forms
from mainboard.models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['subject', 'content']


        labels = {
            'subject': '제목',
            'content': '내용',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

stock/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm, SignupForm

def home(request):
    """
    홈페이지
    """
    
    return render(request, 'common/home.html')

def signup(request):
    """
    계정생성
    """
    
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username') # 이름 가져오기
            raw_password = form.cleaned_data.get('password1') # 비밀번호 가져오기
            user = authenticate(username=username, password=raw_password) # 회원가입 후 자동 로그인 : authenticate
            login(request, user)
            return redirect('mainboard:index')
    else:
        form = SignupForm()
    return render(request, 'common/signup.html', {'form': form})

stock/exchange/views.py
##### 주식 데이터, 그래프 관련 #####
import io
import urllib, base64
import FinanceDataReader as fdr
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.ticker as ticker
import matplotlib.font_manager as fm
from mplfinance.original_flavor import candlestick2_ohlc
########################################################
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf import settings
from .models import Stock_list, User_result, Transaction_history
from common.models import MyUser
from django.utils import timezone
from django.core.paginator import Paginator # 페이징 관련 (글 목록)
from django.db.models import Q # 검색 관련
from datetime import datetime, timedelta


# Create your views here.
def index(request):
    
#  ---------------------------------- 검색  ---------------------------------- #
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어

    # 조회
    stock_list = Stock_list.objects.order_by('stock_name')
    if kw:
        stock_list = stock_list.filter(
            # contains : 대소문자 구분 / icontain : 대소문자 구분x
            Q(symbol__icontains=kw) |  # 종목 번호
            Q(stock_name__icontains=kw)  # 종목 이름 
        ).distinct()
# ---------------------------------------------------------------------------- #

# ----------------------------------- [페이징] --------------------------- #
    # 페이징처리
    paginator = Paginator(stock_list, 20)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'stock_list': page_obj, 'page': page, 'kw': kw}  # page와 kw가 추가되었다.
    print('kw:', kw)

    # context = {'stock_list': stock_list}
    return render(request, 'exchange/stock_list.html', context)
# ----------------------------------- [페이징] --------------------------- #


# 예은 : 그래프 만드는 부분 추가했습니다 (21.02.01)
# 예은 할일 : cur_price를 현재가로 불러오도록 (근데 이렇게하면 실시간 업데이트 or 호가창 필요), 전일대비 몇퍼 증감인지 보여주기
def stock_list_page(request, symbol):
    today = datetime.today()
    yesterday = datetime.today() - timedelta(days=1)
    stock = Stock_list.objects.get(symbol=symbol)

    df_specific = fdr.DataReader(symbol, today.strftime('%Y-%m-%d'))
    stock.cur_price = int(df_specific['Close'][0]) # 맨위 날짜 읽는거니까 오늘 정가 empty여도 가장 최근값 불러옴

    # 전일 데이터 불러오기 (주말, 연휴인 경우 data없으므로 data있을때까지 거슬러올라가기)
    yesterday_stock = fdr.DataReader(symbol, yesterday.strftime('%Y-%m-%d'))
    date = 1
    while (1):
        yesterday_stock = fdr.DataReader(symbol, yesterday.strftime('%Y-%m-%d'), today.strftime('%Y-%m-%d'))
        if (len(yesterday_stock) > 1):
            yesterday_price = int(yesterday_stock['Close'][0])
            break
        else:
            date += 1
            yesterday = datetime.today() - timedelta(days=date)
    yesterday_price = int(yesterday_stock['Close'][0])

    difference = stock.cur_price - yesterday_price
    difference_percent = round((difference / yesterday_price) * 100, 2)
    # 색깔을 위한 Flag
    if difference > 0:
        flag = 1
    elif difference < 0:
        flag = -1
    else:
        flag = 0

    graph_uri = graph(request, symbol)

    context = {'stock': stock, 'data': graph_uri, 'yesterday':yesterday_price, 'difference':difference, 'diff_per':difference_percent, 'flag':flag}
    return render(request, 'exchange/stock_page.html', context)



def find_stock(request):
    if request.user.is_authenticated:
        userID = request.user.id
    stock_requested = str(request.GET.get('stock_name', None))
    stock_list = stock_requested.objects.get(id=stock_name)
    context = {'stock_list': stock_list}
    return render(request, 'exchange/stock_list_page.html', context)


def graph(request, symbol):
    stock = Stock_list.objects.get(symbol=symbol)
    title_font_name = 'sans-serif'
    tick_label_font_name = 'sans-serif'

    # 봉차트 그리기
    now = datetime.now()
    half_year = (now - timedelta(days=180)).strftime('%Y-%m-%d')
    df_specific = fdr.DataReader(symbol, half_year)

    df_specific['MA5'] = df_specific['Close'].rolling(5).mean()
    df_specific['MA10'] = df_specific['Close'].rolling(10).mean()
    df_specific['MA20'] = df_specific['Close'].rolling(20).mean()
    df_specific[['Close','MA5','MA10','MA20']].plot()

    fig = plt.figure(figsize=(20,10))
    ax = fig.add_subplot(111)
    index = df_specific.index.astype('str') # 캔들스틱 x축이 str로 들어감

    # 이동평균선 그리기
    ax.plot(index, df_specific['MA5'], label='5days MA', linewidth=0.7)
    ax.plot(index, df_specific['MA10'], label='10days MA', linewidth=0.7)
    ax.plot(index, df_specific['MA20'], label='20days MA', linewidth=0.7)

    # X축 티커 숫자 20개로 제한
    ax.xaxis.set_major_locator(ticker.MaxNLocator(20))

    # 그래프 title과 축 이름 지정
    # ax.set_title(stock_name, fontsize=22)
    ax.set_xlabel('Date')

    # 캔들차트 그리기
    candlestick2_ohlc(ax, df_specific['Open'], df_specific['High'],
                      df_specific['Low'], df_specific['Close'],
                      width=0.5, colorup='r', colordown='b')
    ax.legend()
    plt.grid()

    plt.plot()
    fig = plt.gcf()
    buf = io.BytesIO()
    fig.savefig(buf, format='png')
    buf.seek(0)
    string = base64.b64encode(buf.read())
    uri = urllib.parse.quote(string)
    return uri


# get username, stockID, quantity from get request 
# find cur_price from Stock_list
# find cash from MyUser
# return : cash, cur_price

def request_stockinfo(userID, stockID):
    cur_price = int(Stock_list.objects.get(symbol=stockID).cur_price)
    cur_cash = int(MyUser.objects.get(id=userID).cash)
    return (cur_price, cur_cash)

# returns whether buy is possible
def judge_buy(cash, cur_price, quantity):
    
    if cash < cur_price * quantity:
        return False
    else:
        return True

# returns whether sell is possible
def judge_sell(userID, stockID, quantity):
    #Check if user has enough stocks to sell
    try:
        user_result = User_result.objects.get(user_ID=userID, stock_ID=stockID)
        if user_result.total_Qty < quantity:
            return False
        else:
            return True
    except:
        return False


###################################################
# function buy() : Buy Stocks                     #
# url : /buy?stockID=XXXXXX&quantity=YYYYYY       #
# stockID = XXXXXX                                #
# quantity = YYYYYY                               #
# 1. Check if user has enough stock : judge_buy() #
# 2. Save Transaction_history                     #
# 3. update user.cash, user_result.total_Qty      #
#    (function : transaction_save())              #
###################################################
def buy(request):
    if request.user.is_authenticated:
        userID = request.user.id
    stockID = str(request.GET.get('stockID', None))
    quantity = int(request.GET.get('quantity', None))
    ##Add Check if quantity is 0

    ########################
    user = MyUser.objects.get(id=userID)
    stock = Stock_list.objects.get(symbol=stockID)
    cur_price = int(stock.cur_price)
    cur_cash = int(user.cash)

    buy_available = judge_buy(cur_cash, cur_price, quantity)
    if buy_available:
        #save transaction history
        new_transaction = Transaction_history(Qty=quantity, cur_price=cur_price, date=str(timezone.now()), purchase=1, stock_ID=stock, user_ID=user)
        new_transaction.save()
        #Update user_result
        transaction_save(user, stock, quantity, 1)
        updated_cash = user.cash
        #Buy Success
        return HttpResponse("Buy Success : userID %s, quantity %s, Old cash %s, Current cash %s, cur_price : %s" % (userID, quantity, cur_cash, updated_cash, cur_price))
    else:
        #Buy Failed
        return HttpResponse("Buy Failed : userID %s, quantity %s, Current cash %s, cur_price : %s, need more : %s" % (userID, quantity, cur_cash, cur_price, cur_price*quantity-cur_cash))


###################################################
# function sell() : sell Stocks                   #
# url : /sell?stockID=XXXXXX&quantity=YYYYYY      #
# stockID = XXXXXX                                #
# quantity = YYYYYY                               #
# 1. Check if user has enough stock : judge_sell()#
# 2. Save Transaction_history                     #
# 3. update user.cash, user_result.total_Qty      #
#    (function : transaction_save())              #
###################################################
def sell(request):
    if request.user.is_authenticated:
        userID = request.user.id
    stockID = str(request.GET.get('stockID', None))
    quantity = int(request.GET.get('quantity', None))
    ##Add Check if quantity is 0

    ########################
    user = MyUser.objects.get(id=userID)
    stock = Stock_list.objects.get(symbol=stockID)
    cur_price = int(stock.cur_price)
    cur_cash = int(user.cash)
    sell_available = judge_sell(user.id, stock.id, quantity)
    user_result = User_result.objects.get(user_ID=userID, stock_ID=stock.id)

    if sell_available:
        #save transaction history
        new_transaction = Transaction_history(Qty=quantity, cur_price=cur_price, date=str(timezone.now()), purchase=0, stock_ID=stock, user_ID=user)
        new_transaction.save()
        #Update user_result
        transaction_save(user, stock, quantity, 0)
        updated_cash = user.cash
        # Sell Success
        return HttpResponse("Sell Success : userID %s, sell quantity %s,remain quantity %s, Old cash %s, Current cash %s, cur_price : %s" % (userID, quantity, user_result.total_Qty, cur_cash, updated_cash, cur_price))
    else:
        # Sell failed
        return HttpResponse("Sell Failed : userID %s, quantity %s" % (userID, quantity))




#########################################################
# function transaction_save() : update user_result      #
# type : buy = 1, sell = 0                              #
# 1. Buy                                                #
#   1) Check if user has user_result with same stock.id #

stock/mainboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.utils import timezone
from .forms import ArticleForm, CommentForm
from .models import Article, Comment
from django.core.paginator import Paginator





def index(request):
    article_list = Article.objects.order_by('-create_date')

        # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지

        # 페이징처리
    paginator = Paginator(article_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'article_list': page_obj}
    # context = {'article_list' : article_list} <- 페이징하면서 사라짐


    # return HttpResponse("안녕하세요 pybo에 오신것을 환영합니다.")
    return render(request, 'article_list.html', context)

def detail(request, article_id):
    #article = Article.objects.get(id=article_id)
    article = get_object_or_404(Article, pk = article_id)
    context = {'article': article}
    return render(request, 'article_detail.html', context)



def article_create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.create_date = timezone.now()
            article.save()
            return redirect('mainboard:index')
    else:
        form = ArticleForm()
    context = {'form': form}
    return render(request, 'article_form.html', context)





# def comment_create(request, article_id):
#     article = get_object_or_404(Article, pk=article_id)
#     article.comment_set.create(content=request.POST.get('content'), create_date=timezone.now())
#     return redirect('mainboard:detail', article_id=article.id)

def comment_create(request, article_id):
    
    article = get_object_or_404(Article, pk=article_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.create_date = timezone.now()
            comment.article = article
            comment.save()
            return redirect('mainboard:detail', article_id=article.id)
    else:
        form = CommentForm()
    context = {'article': article, 'form': form}
    return render(request, 'article_detail.html', context)

stock/rest_api/views.py
import json
from django.shortcuts import render
from django.views.generic import View
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

# Create your views here.


@method_decorator(csrf_exempt, name="dispatch")
class IndexView(View):
    def get(self, request):
        return

    def post(self, request):
        data = json.loads(request.body)
        print(data)
        return HttpResponse(status=200)

stock/templates/exchange/exchange.html
"hi"

stock/templates/exchange/exchange_base.html
<!------------------- ↓검색 기능↓ ---------------------->
<div class="row justify-content-end my-3">
    <div class="col-4 input-group">
        <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}" id="enter_search">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" id="btn_search">종목 찾기</button>
        </div>
    </div>
</div>
<!------------------- ↑검색 기능↑ ---------------------->

stock/templates/exchange/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

stock/templates/exchange/mypage.html
<!DOCTYPE html>
{% extends 'temp_base.html' %}
{% block content %}
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>Title</title>
        </head>
        <body>

            <ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">주식 보유 현황</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">매수/매도 내역</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Contact</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    <table class="table">
                <thead>
                    <tr>
                        <th>종목이름</th>
                        <th>보유랑</th>
                        <th>매수단가</th>
                    </tr>
                </thead>
                <tbody>
                    {% if user_result %}
                        {% for result in user_result %}
                            <tr>
                                <td>{{ result.stock_ID.stock_name }}</td>
                                <td>{{ result.total_Qty }}</td>
                                <td>{{ result.avg_purchase_price }}</td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="3">보유한 종목이 없습니다.</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
  </div>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
    <table class="table">
                <thead>
                    <tr>
                        <th>유저이름</th>
                        <th>종목</th>
                        <th>매수/매도</th>
                        <th>수량</th>
                        <th>단가</th>
                    </tr>
                </thead>
                <tbody>
                    {% if transactions %}
                        {% for transaction in transactions %}
                            <tr>
                                <td>{{ transaction.user_ID.username }}</td>
                                <td>{{ transaction.stock_ID.stock_name }}</td>
                                {% if transaction.purchase %}
                                    <td>매수</td>
                                {% else %}            
                                    <td>매도</td>
                                {% endif %}
                                <td>{{ transaction.Qty }}</td>
                                <td>{{ transaction.cur_price }}</td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="3">보유한 종목이 없습니다.</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
  
  </div>
  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
</div>

</body>
</html>
{% endblock %}

stock/templates/exchange/stock_list.html
{% extends 'temp_base.html' %}
{% comment %} {% extends 'exchange/exchange_base.html' %} {% endcomment %}
{% comment %} {% load pybo_filter %} {% endcomment %}
{% block content %}
<div class="container my-3">

<!-- ------------------------------- 검색기능  -------------------------------- -->
    <div class="row justify-content-end my-3">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}" id="enter_search">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">종목 찾기</button>
            </div>
       </div>
    </div>
<!-- ------------------------------- 검색기능 -------------------------------- -->





    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>시장</th>
            <th>종목 번호</th>
            <th>종목 이름</th>
            <th>현재가</th>
        </tr>
        </thead>
        <tbody>
        {% if stock_list %}
        {% for stock in stock_list %}
        <tr>
            <td>{{ stock.market_name }}</td>
            <td>{{ stock.symbol }}</td>
            <td>
                <a href="{% url 'exchange:stock_list_page' stock.symbol %}">{{ stock.stock_name }}</a>
            </td>
            <td>{{ stock.cur_price }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">검색 요청에 맞는 종목이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
<!-- ------------------------------- [edit] -------------------------------- -->
<div class="row justify-content-end my-3">
    <div class="col-4 input-group">
        <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}" id="enter_search">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" id="btn_search">종목 찾기</button>
        </div>
    </div>
</div>
<!-- ------------------------------- [edit] -------------------------------- -->
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if stock_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ stock_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in stock_list.paginator.page_range %}
            {% if page_number >= stock_list.number|add:-5 and page_number <= stock_list.number|add:5 %}
            {% if page_number == stock_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if stock_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ stock_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
<!-- ----------------------------------------------------------------------- -->    
</div>
<!-- ------------------------------- form -------------------------------- -->
<form id="searchForm" method="get" action="{% url 'exchange:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
<!-- ----------------------------------------------------------------------- -->

{% endblock %}

<!-- ------------------------------- 페이징과 검색을 처리하는 자바 스크립트 코드(검색 관련) -------------------------------- -->
{% block script %}
<script type='text/javascript'>
$(document).ready(function (){
    // 페이지 클릭
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    // 클릭으로 종목 검색
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

    // 엔터키 종목 검색
    $("#enter_search").on('keyup', function() {
        if( event.keyCode == 13 ){
            $("#kw").val($(".kw").val());
            $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
            $("#searchForm").submit();
        }
    });
});
</script>
{% endblock %}
<!-- ------------------------------- 페이징과 검색을 처리하는 자바 스크립트 코드(검색 관련) -------------------------------- -->